name: CICD Pipeline to deploy the Application
run-name: Deploy Application to AWS by ${{ github.actor }} on ${{ github.run_id }}
on:
  push:
    branches:
      - main
jobs:
  CI_Job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
        
      - name: Install Linter 
        run: | 
          pip install flake8 
          flake8 
        working-directory: weather

      - name: Testing the Code
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest 
        working-directory: weather

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: weather
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/weather:${{ github.run_id}}
        

  CI_JOB_Auth:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.1' # The Go version to download (if necessary) and use.

      - name: Install Linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
          export PATH=$PATH:$HOME/go/bin
          golangci-lint run ./auth
        working-directory: auth
        continue-on-error: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          context: auth
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/auth:${{ github.run_id}}
     
