name: CICD Pipeline to deploy the Application
run-name: Deploy Application to AWS by ${{ github.actor }} on ${{ github.run_id }}
on:
  push:
    branches:
      - main
jobs:
  CI_Job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
        
      - name: Install Linter 
        run: | 
          pip install flake8 
          flake8 
        working-directory: weather
      
      - name: Unittest
        run: |
          APIKEY= 0da866860fmshdc1cca700d3c89dp17cffdjsn0dc10ba9c00a
          pip install -r requirements.txt
          pip install pytest
          pytest -v
        working-directory: weather

#      - name: Unittest
#        run: |
#          export APIKEY=${{ secrets.APIKEY}}
#          echo "APIKEY is ${APIKEY}"
#          pip install -r requirements.txt
#          pip install pytest
#          pytest -v
#        working-directory: weather