name: setup ALB over EKS
run-name: setup ALB over EKS by ${{ github.actor }} 
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      cluster:
        description: 'EKS Cluster Name'
        required: true
        default: 'my-cluster'
      install_alb:
        description: 'Install AWS Load Balancer Controller'
        required: true
        options:
          - 'yes'
          - 'no'
        type: choice

permissions:
  id-token: write    # ✅ Required for OIDC
  contents: read
jobs:
  setupalb:
    if: ${{ github.event.inputs.install_alb == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout  
        uses: actions/checkout@v4

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::610952688122:role/testoidc
          aws-region: ${{ github.event.inputs.region }}

      - name: enable cluster to use IRAC
        run: |
          eksctl utils associate-iam-oidc-provider \
          --cluster ${{ github.event.inputs.cluster }} \
          --approve
      - name: download IAM role
        run: |
          curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.11.0/docs/install/iam_policy.json
          aws iam create-policy \
          --policy-name AWSLoadBalancerControllerIAMPolicy \
          --policy-document file://iam_policy.json
        continue-on-error: true
        
      - name: service account for ALB
        run: |
          eksctl create iamserviceaccount \
            --cluster=${{ github.event.inputs.cluster }} \
            --namespace=kube-system \
            --name=aws-load-balancer-controller \
            --attach-policy-arn=arn:aws:iam::610952688122:policy/AWSLoadBalancerControllerIAMPolicy \
            --override-existing-serviceaccounts \
            --approve
        ### Change this ^^^ Account ID 

      - name: verify service account
        run: |
          eksctl get iamserviceaccount \
          --cluster=${{ github.event.inputs.cluster }} \
          --name=aws-load-balancer-controller \
          --namespace=kube-system

      - name: cert manager
        run: |
          kubectl apply \
          --validate=false \
          -f https://github.com/jetstack/cert-manager/releases/download/v1.13.5/cert-manager.yaml
      
      - name: install AWS Load Balancer Controller
        run: |
          curl -Lo v2_11_0_full.yaml https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.11.0/v2_11_0_full.yaml

      - name: edite in v2_11_0_full.yaml
        run: |
          sed -i.bak -e '690,698d' ./v2_11_0_full.yaml
          sed -i.bak -e 's|your-cluster-name|${{ github.event.inputs.cluster }}|' ./v2_11_0_full.yaml
          kubectl apply -f v2_11_0_full.yaml

      - name: download ingress class
        run: |
          curl -Lo v2_11_0_ingclass.yaml https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.11.0/v2_11_0_ingclass.yaml
          kubectl apply -f v2_11_0_ingclass.yaml
          
  uninstall:
    if: ${{ github.event.inputs.install_alb == 'no' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout  
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::610952688122:role/testoidc
          aws-region: ${{ github.event.inputs.region }}
          
      - name: delete IAM role policy
        run: |
          aws iam delete-policy \
            --policy-arn arn:aws:iam::610952688122:policy/AWSLoadBalancerControllerIAMPolicy

